name: CI
on:
  push:

permissions:
  contents: read 

jobs:
  test:
    runs-on: 
      - ubuntu-latest
      - macos-latest
      - windows-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build test
